# Generated by Django 3.0.2 on 2020-10-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200930_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(11, 'student'), (12, 'counsel')], null=True),
        ),
    ]
