# Generated by Django 3.0.2 on 2020-10-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('STUDENT', 'student'), ('COUNSEL', 'counsel')], null=True),
        ),
    ]
