# Generated by Django 3.0.2 on 2020-10-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201006_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('student', 'student'), ('counsel', 'counsel')], null=True),
        ),
    ]
