# Generated by Django 3.0.2 on 2020-10-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20201006_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('counsel', 'counsel'), ('dean', 'dean')], max_length=20, null=True),
        ),
    ]
