# Generated by Django 3.0.2 on 2020-10-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_type',
        ),
    ]
