# Generated by Django 3.0.2 on 2020-07-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_start',
            field=models.TimeField(),
        ),
    ]
