# Generated by Django 3.0.2 on 2020-10-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems', models.CharField(blank=True, choices=[('lonely', 'lonely'), ('eating', 'eating'), ('worry', 'worry')], max_length=200, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='counsel.Appointment')),
            ],
        ),
    ]
