# Generated by Django 3.0.2 on 2020-10-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0002_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='parents',
            field=models.CharField(blank=True, choices=[('father', 'father'), ('mother', 'mother'), ('both', 'both'), ('none', 'none')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='relationship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='siblings',
            field=models.IntegerField(default=0),
        ),
    ]
