# Generated by Django 3.0.2 on 2020-10-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages', '0003_auto_20190617_1316'),
        ('counsel', '0003_auto_20201008_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_messages.Message'),
        ),
    ]
